#!/usr/bin/ansible-playbook
---
- name: k8s setup
  hosts: all
  become: true

  vars:
    pkgs_cache: true

  # Create lxd containers for local testing  
  pre_tasks:
  - name: Create container when using lxd
    import_role: name=lxd_inventory
    when: ansible_connection is defined and ansible_connection == 'lxd'

  tasks:
  # local yum cache
  - import_tasks: tasks/pkgs_cache.yml
    when: pkgs_cache is defined and pkgs_cache == true

  # Install Docker and kubadm
  - name: install & configure docker
    import_role: name=docker
  - name: install kubeadm, kubelet & kubeclt
    import_role: name=kubeadm

  # bootstrap k8s cluster
  - name: bootstrap k8s
    import_role: name=k8s_init
