---
# file: roles/kubeadm/tasks/docker_prep.yml

- name: docker config directory created
  file: path=/etc/docker state=directory
  tags: docker_config
    
- name: docker daemon.json created
  copy:
    dest: /etc/docker/daemon.json
    content: | 
      {
        "exec-opts": ["native.cgroupdriver=systemd"],
        "log-driver": "json-file",
        "log-opts": {
          "max-size": "100m"
        },
        "storage-driver": "overlay2",
        "storage-opts": [
          "overlay2.override_kernel_check=true"
        ]
      }
  notify: docker restarted
  tags: docker_config
