---
# file: roles/kubeadm/tasks/main.yml

- import_tasks: system_prep.yml
- import_tasks: docker_config.yml

- import_tasks: k8s_repo.yml
  when: use_local_repo is not defined
  tags: k8s_repo

- name: k8s packages to be installed
  debug: var=k8s_packages
  tags: ['never', 'debug']

- name: k8s packages installed
  yum: name="{{ k8s_packages }}"
  notify: kubelet restarted
  tags: k8s_install

- meta: flush_handlers

- name: kubelet started
  systemd: name=kubelet enabled=true state=started
  tags: k8s_install