---
# file: roles/docker/defaults/main.yml

docker_prerequsits:
  - python-docker-py
  - device-mapper-persistent-data
#  - lvm2

docker_packages:
#  - docker-ce-18.06.2.ce
  - containerd.io-1.2.13
  - docker-ce-19.03.11
  - docker-ce-cli-19.03.11
