---
# file: k8s_init/tasks/k8s_init.yml

# Set VIP init options
- import_tasks: kubevip.yml
  when: k8s_vip is defined

- name: set kubeadm init options for vip 
  set_fact: kubeadm_init="{{ kubeadm_init + ' --control-plane-endpoint=' + k8s_vip }}"
  when: k8s_vip is defined
  tags: debug

- name: set kubeadm init options for cni
  set_fact: kubeadm_init="{{ kubeadm_init + k8s_cni_init | default(omit) }}"
  when: k8s_cni_init is defined
  tags: debug

# Debug
- block:
  - debug: var=kubeadm_init
  - debug: var=kubeadm_config
  tags: ['never', 'debug']

- name: kubeadm init
  command: 
    cmd: "{{ kubeadm_init }}" 
    creates: /etc/kubernetes/admin.conf
  when: kubeadm_config is undefined

- name: kubeadm init with '--config'
  block:
  - name: create kubeadm-config.yml
    copy: content="{{ kubeadm_config }}" dest=/tmp/kubeadm-config.yaml
  - name: kubeadm init
    command: 
      cmd: kubeadm init --config=/tmp/kubeadm-config.yaml
      creates: /etc/kubernetes/admin.conf
  when: kubeadm_config is defined