
# Configure kubeclt on ansible machine
- name: get kubectl path
  shell: which kubectl
  register: kubectl_path
  changed_when: false
  ignore_errors: true

- name: copy kubectl
  fetch:
    src: '{{ (kubectl_path.stdout |length > 0) 
      | ternary(kubectl_path.stdout, "/usr/bin/kubectl") }}'
    dest: cache/
    flat: true

- name: apply exe permission for kubectl 
  local_action: file mode=774 path="{{ playbook_dir }}/cache/kubectl"
  become: no
  
- name: copy kube conf
  fetch: src=/etc/kubernetes/admin.conf dest=cache/ flat=true

- name: create kubectl wrapper
  copy:
    content: KUBECONFIG={{ playbook_dir }}/cache/admin.conf  {{ playbook_dir }}/cache/kubectl $@
    dest: kctl
    force: yes 
    mode: 750
  become: no
  delegate_to: localhost
